### ISSUE TITLE
great work! i'm interested in this but example page still not updated?

### ISSUE THREAD

**Issue by hiqsociety** [realPy/hogosuru#143]
great work! i'm interested in this but example page still not updated?

possible to show the example single page app first? will be better if hv a minimal pwa too but single page app will suffice .

**Comment by realPy** [comment]
have you read documentation here https://hogosuru.v-ip.fr/?
example use in doc up to date here 

https://github.com/realPy/learn-hogosuru

**Comment by hiqsociety** [comment]
yup i read it.
this page is what i mean
https://hogosuru.v-ip.fr/guides/create-a-single-app-with-hogosuru/example

**Comment by realPy** [comment]
Click on "create a single app with hogosuru" it's the pattern of the doc that create empty page.

Yes hogosuru is used in production for several of my product. There was one big project but I can't tell which. It's a iot project.

**Comment by realPy** [comment]
You can go to the discord channel if you wan help

**Comment by hiqsociety** [comment]
ok. i will, been busy lately with backend stuff. will do so thx.
