### ISSUE TITLE
Add forEach() for nodeList Element

### ISSUE THREAD

**Issue by YukiNokumo** [realPy/hogosuru#146]
Is actually not possible to iterate natively in nodeList element.

See https://developer.mozilla.org/fr/docs/Web/API/NodeList/forEach

In the meantime, do :
```go
menuSelector, _ := d.QuerySelectorAll(".navbar-item")

for i := 0; i < menuSelector.Length(); i++ {
    item, _ := menuSelector.Item(i)
}
```

**Comment by realPy** [comment]
Just test on a project and your code work.

`
		menuSelector, _ := d.QuerySelectorAll(".navbar-item")

					for i := 0; i < menuSelector.Length(); i++ {
						item, _ := menuSelector.Item(i)
						fmt.Printf("%v\n", item)
					}

`
show me :

<object>
<object>
<object>
<object>
<object>
