### ISSUE TITLE
awesome

### ISSUE THREAD

**Issue by gedw99** [realPy/hogosuru#36]
this is really useful and impressive. its really nice of you to make this..

Will be using this with gio

https://github.com/gioui/gio
https://github.com/gioui/gio-x

**Comment by realPy** [comment]
Thanks for your message! You can safely use hogosuru , the base code is stable and will not be change in the future , more functionality will be added soon.  
Gio is also an interesting project. 
You can message me if you find bug or need an api that hogosuru don't yet support.

If you like the project star it ! 👍

**Comment by gedw99** [comment]
will do..

**Comment by realPy** [comment]
@gedw99 i close this issue .
Thanks for your support!
I suggested to see hogosurutoaster, the first hogosuru component :)
